### PR TITLE
chore(config): remove crosswalk from config.xml

### PR DESCRIPTION
**Pull request by pwespi**
Crosswalk is no longer actively developed and the market share of Android<5.0 is declining, so I don't think the "gold standard" ionic app should include it by default anymore. Also ionic2-app-base doesn't include it.

### CODE REVIEW

**Comment by mohamedsharaf** [comment]
i vote for this too

**Comment by mohamedsharaf** [comment]
it add extra 20mb space and webview is now auto-updated with android

When Intel started the Crosswalk Project in 2013, our goal was to bring the full power of the web platform to mobile and desktop application developers. Since then, the environment has evolved and Progressive Web Apps bring the power of native apps to pure web applications. Now, the Android platform Webview shares code and features with the Chrome browser and is kept up-to-date, while Electron and Intel’s NW.JS support most desktop developers. As a result, we believe Crosswalk has done its job and we can make a bigger impact focusing on other areas of the web platform.

Crosswalk 23 is our last stable release. After that we will no longer fix specific bugs but will leave the source code and binaries available for Crosswalk users to continue building applications. We welcome help from the Crosswalk community and would not discourage anybody willing to maintain the project.

We value your contributions and involvement with Crosswalk. The Open Source Technology Center Web Technology team at Intel will continue to drive adoption of new web technologies in new areas, and we look forward to introducing new projects that will drive the web platform forward.

Thank you for using Crosswalk!
https://crosswalk-project.org/blog/crosswalk-final-release.html

**Comment by sam-suresh** [comment]
Please merge this. Crosswalk cause build fail because the plugin download URL unavailable. 

`FAILURE: Build failed with an exception.
        
        * What went wrong:
        A problem occurred configuring root project 'android'.
        > Could not resolve all dependencies for configuration ':_armv7DebugApkCopy'.
            > Could not resolve org.xwalk:xwalk_core_library:22+.
              Required by:
                  project :
               > Could not resolve org.xwalk:xwalk_core_library:22+.
                  > Failed to list versions for org.xwalk:xwalk_core_library.
                     > Unable to load Maven meta-data from 
        https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml.
                        > Could not GET 
        'https://download.01.org/crosswalk/releases/crosswalk/android/maven2/org/xwalk/xwalk_core_library/maven-metadata.xml'. 
        Received status code 503 from server: Service Unavailable`

**Comment by brandyscarney** [comment]
Thank you for the PR!

**Pull request merged**
